import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Nebulook",
  description: "Nebulook Terms of Service. Read before using the app.",
};

export default function TermsPage() {
  return (
    <article className="max-w-3xl mx-auto px-6 py-16 md:py-24 prose-custom">
      <h1 className="text-3xl md:text-4xl font-bold mb-2">Terms of Service</h1>
      <p className="text-foreground/50 mb-10">
        Effective Date: March 2026 &middot; Last Updated: March 2026
      </p>

      <p>
        These Terms of Service (&quot;Terms&quot;) govern your use of Nebulook (the &quot;App&quot;), operated by Jex Global Inc. (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). By downloading, installing, or using Nebulook, you agree to be bound by these Terms. If you do not agree, do not use the App.
      </p>

      <h2 className="text-2xl font-bold mt-10 mb-4">1. Description of Service</h2>
      <p>
        Nebulook is an AI-powered outfit recommendation app that scans your wardrobe, builds a digital closet, and generates personalized outfit suggestions based on your style preferences, weather conditions, and daily activities.
      </p>
      <p className="mt-3 font-semibold">
        Nebulook is NOT a personal stylist service, fashion retailer, or clothing marketplace. See Section 8 (Disclaimers) for important limitations.
      </p>

      <h2 className="text-2xl font-bold mt-10 mb-4">2. Eligibility</h2>
      <p>You must be at least 13 years of age to create an account and use Nebulook. If you are under 18, you must have parental or guardian consent. By using the App, you represent that you meet these requirements.</p>

      <h2 className="text-2xl font-bold mt-10 mb-4">3. Your Account</h2>
      <p>You may create one account per person. You are responsible for maintaining the security and confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use of your account. We are not liable for any loss resulting from unauthorized access to your account.</p>

      <h2 className="text-2xl font-bold mt-10 mb-4">4. Subscriptions &amp; Payments</h2>
      <ul className="list-disc pl-6 space-y-2 text-foreground/70">
        <li><strong>Nebulook Premium</strong> is available as a monthly or annual subscription.</li>
        <li>Payment is charged to your Apple ID at the time of purchase confirmation.</li>
        <li>Subscriptions <strong>auto-renew</strong> unless canceled at least 24 hours before the end of the current billing period.</li>
        <li>You can manage or cancel your subscription in iPhone Settings &gt; [Your Name] &gt; Subscriptions.</li>
        <li>Refunds are handled by Apple in accordance with their refund policy.</li>
        <li>Prices are subject to change. We will notify you of any price changes before they take effect.</li>
      </ul>

      <h2 className="text-2xl font-bold mt-10 mb-4">5. User Content &amp; Data</h2>
      <ul className="list-disc pl-6 space-y-2 text-foreground/70">
        <li>You <strong>own</strong> your photos and closet data. We do not claim ownership of any content you upload to Nebulook.</li>
        <li>You grant us a limited, non-exclusive license to process your photos and data solely to provide, maintain, and improve the App&apos;s services to you.</li>
        <li>Uploaded photos are processed by AI to detect garments. We do not use your photos for advertising, marketing, or model training.</li>
        <li>You are responsible for ensuring you have the right to upload any photos you submit.</li>
      </ul>

      <h2 className="text-2xl font-bold mt-10 mb-4">6. AI-Generated Content</h2>
      <ul className="list-disc pl-6 space-y-2 text-foreground/70">
        <li>Outfit recommendations are generated by artificial intelligence and are suggestions only.</li>
        <li>AI-generated outfit previews are approximate visualizations and may not perfectly represent real-world appearance.</li>
        <li>We do not guarantee the accuracy, suitability, or completeness of any AI-generated recommendations.</li>
      </ul>

      <h2 className="text-2xl font-bold mt-10 mb-4">7. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul className="list-disc pl-6 space-y-2 text-foreground/70">
        <li>Use the App for any unlawful purpose.</li>
        <li>Attempt to reverse-engineer, decompile, or disassemble the App.</li>
        <li>Interfere with or disrupt the App&apos;s infrastructure.</li>
        <li>Create multiple accounts or share account access.</li>
        <li>Upload content that is offensive, harmful, or infringes on the rights of others.</li>
        <li>Use the App to transmit malicious code or content.</li>
      </ul>

      <h2 className="text-2xl font-bold mt-10 mb-4">8. Disclaimers</h2>
      <div className="bg-primary-subtle border border-primary/20 rounded-xl p-6 space-y-3 text-foreground/80">
        <p><strong>IMPORTANT — PLEASE READ CAREFULLY:</strong></p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Nebulook is for <strong>personal styling assistance ONLY</strong>.</li>
          <li>Outfit recommendations are <strong>AI-generated suggestions</strong>, not professional styling advice.</li>
          <li>AI outfit previews are <strong>approximate visualizations</strong> and may differ from real-world appearance.</li>
          <li>Weather-based recommendations rely on third-party weather data which may not always be accurate.</li>
          <li>We are <strong>not responsible</strong> for any decisions you make based on outfit suggestions provided by the App.</li>
          <li>Garment detection accuracy depends on image quality and may not be 100% accurate for all items.</li>
        </ul>
      </div>

      <h2 className="text-2xl font-bold mt-10 mb-4">9. Limitation of Liability</h2>
      <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:</p>
      <ul className="list-disc pl-6 space-y-2 text-foreground/70">
        <li>The App is provided <strong>&quot;AS IS&quot;</strong> and <strong>&quot;AS AVAILABLE&quot;</strong> without warranties of any kind, whether express or implied, including but not limited to merchantability, fitness for a particular purpose, and non-infringement.</li>
        <li>We shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the App.</li>
        <li>Our total aggregate liability to you for any claims arising from your use of the App shall not exceed the amount you paid us in the twelve (12) months preceding the claim.</li>
      </ul>

      <h2 className="text-2xl font-bold mt-10 mb-4">10. Termination</h2>
      <ul className="list-disc pl-6 space-y-2 text-foreground/70">
        <li>You may delete your account at any time through the App.</li>
        <li>We may suspend or terminate your account if you violate these Terms.</li>
        <li>Upon termination, your data will be handled in accordance with our <a href="/privacy" className="text-primary">Privacy Policy</a>.</li>
        <li>Sections that by their nature should survive termination (including Disclaimers, Limitation of Liability, and Governing Law) will survive.</li>
      </ul>

      <h2 className="text-2xl font-bold mt-10 mb-4">11. Governing Law</h2>
      <p>These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict of law provisions. Any disputes arising from these Terms or your use of the App shall be resolved in the courts located in the State of Delaware.</p>

      <h2 className="text-2xl font-bold mt-10 mb-4">12. Changes to These Terms</h2>
      <p>We reserve the right to modify these Terms at any time. We will notify you of material changes through the App or via email. Your continued use of the App after changes constitutes acceptance of the updated Terms.</p>

      <h2 className="text-2xl font-bold mt-10 mb-4">13. Contact Us</h2>
      <p>If you have questions about these Terms, contact us at:</p>
      <p className="mt-2">
        <strong>Jex Global Inc.</strong>
        <br />
        Email: <a href="mailto:support@jexhq.com" className="text-primary">support@jexhq.com</a>
      </p>
    </article>
  );
}
